# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'libraryManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for libraryManagement


# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Database'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods	
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'


# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'

end
